version: '0.1.0'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - RUN_FRONTEND=${RUN_FRONTEND}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - RUN_BACKEND=${RUN_BACKEND}
    ports:
      - "5000:5000"
